name: CI_workflow

on: 
  pull_request:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.8.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          make install-requirements

      - name: Run tests with pytest
        run: make test

      - name: Run test coverage
        run: |
          make test-coverage

      - name: Run lints
        run: |
          make lints
